#!/usr/bin/env node
/**
 * gen-tokens.mjs — ONE source of truth for Rollout's design tokens.
 *
 * Emits the token region of src/app/globals.css between the markers
 *   /* ═══ TOKENS:BEGIN (generated by scripts/gen-tokens.mjs — do not hand-edit) ═══ *\/
 *   /* ═══ TOKENS:END ═══ *\/
 * Before the Copper Map restyle (2026-09) the palette was declared FIVE times by
 * hand — :root (dark), :root[data-theme='light'] + .shop-layout[data-theme='light']
 * + .light-scope (light), the prefers-color-scheme media copy of light, the
 * .shop-layout[data-theme='dark'] console block, and .on-dark — and they had
 * already drifted (the light copy lived twice verbatim, the alias block only
 * once). Generating them keeps the theme machinery run 12 verified — the
 * rollout_theme cookie stamped on <html>, the console's own data-theme, the
 * .light-scope subtree, the frozen-dark .on-dark surface — and makes a retoken
 * one edit.
 *
 * Values are 6F "Copper Map" (rollout/docs/restyle/mockups/d6f.html and its
 * generator make-d6f.py). Where 6F does not name a step Rollout needs (bg-1/3,
 * surface-2, text-4, line-strong) the value is DERIVED and marked so.
 *
 * The old names stay. `--gold` is referenced by ~1,900 inline styles as both a
 * fill and a text colour; it now resolves to copper: `--ember` on dark (#d8894a,
 * 5.6:1 on the graphite ground, so it clears AA as text too) and on LIGHT to
 * the stroke copper #a2601f (4.9:1 on #efeeea as text, 5.5:1 under white ink as
 * a fill) — 6F's pure light fill #b87231 fails as text at 3.4:1, so code that
 * wants that exact fill uses `--ember` directly. New surfaces use the new
 * names; old ones follow the alias for free.
 *
 * Usage:  node scripts/gen-tokens.mjs          (rewrite the region in place)
 *         node scripts/gen-tokens.mjs --check  (exit 1 if the region is stale)
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const CSS = path.join(HERE, '..', 'src', 'app', 'globals.css');
const BEGIN = '/* ═══ TOKENS:BEGIN (generated by scripts/gen-tokens.mjs — do not hand-edit) ═══ */';
const END = '/* ═══ TOKENS:END ═══ */';

// ── The copper accent — carried in BOTH themes (6F) ──────────────────────────
const COPPER = {
    ember: '#d8894a', // muted copper — glow · fills · route · pin cores (dark)
    emberText: '#e8a56a', // copper TEXT on a dark surface — 8.11:1 on #1c1c1f
    emberInk: '#8f4f16', // copper TEXT on a light ground — 5.49:1 on #efeeea
    emberLift: '#ecab72', // lighter top of a copper fill (dark)
    emberOn: '#20120a', // ink ON a copper fill — 6.59:1
    lightFill: '#b87231', // 6F light-ground fill — 4.76:1 under --ember-on
    lightLift: '#cf8241',
    lightStroke: '#a2601f', // 6F light-ground strokes — also the AA text copper
};

// ── Per-theme token sets. Keys are Rollout's existing names + 6F's new ones. ──
const DARK = {
    // grounds — 6F: page #1c1c1f, band #161618, stage #121214; surfaces lighter (glass composites to #2a2a2e)
    '--bg-0': '#1c1c1f',
    '--bg-1': '#212126', // DERIVED: 6F --map-panel — first lift off the ground
    '--bg-2': '#161618', // 6F --bg-2: the darker band
    '--bg-3': '#2a2a2e', // 6F glass composite / --pop
    '--stage': '#121214',
    '--surface': '#2a2a2e',
    '--surface-2': '#33333a', // DERIVED: one step lighter than --surface
    '--pop': '#2a2a2e',
    '--pop-line': 'rgba(255, 255, 255, 0.14)',
    // lines — 6F --line .12, --line-2 .20
    '--line': 'rgba(255, 255, 255, 0.12)',
    '--line-mid': 'rgba(255, 255, 255, 0.20)',
    '--line-strong': 'rgba(255, 255, 255, 0.32)', // DERIVED
    '--frame': 'rgba(255, 255, 255, 0.14)',
    // ink — 6F warm neutral ramp
    '--text': '#efeeea',
    '--text-2': '#c6c2b8',
    '--text-3': '#9d998e',
    '--text-4': '#6f6b62', // DERIVED: the disabled step
    '--warn': '#ff5c4d',
    // accent — the old name resolves to copper
    '--gold': COPPER.ember,
    '--gold-dim': 'rgba(216, 137, 74, 0.13)', // 6F --accent-soft
    '--gold-glow': 'rgba(216, 137, 74, 0.08)',
    '--on-gold': COPPER.emberOn,
    '--ember': COPPER.ember,
    '--ember-text': COPPER.emberText,
    '--ember-ink': COPPER.emberInk,
    '--ember-lift': COPPER.emberLift,
    '--ember-on': COPPER.emberOn,
    '--accent-soft': 'rgba(216, 137, 74, 0.13)',
    '--accent-line': 'rgba(216, 137, 74, 0.42)',
    '--accent-glow': COPPER.ember,
    '--accent-ink': COPPER.emberText,
    '--neon': '#84e12e',
    '--orange': '#ff8000',
    '--blue': '#54c3ea',
    // chrome that cannot be a flat surface
    '--header-bg': 'rgba(28, 28, 31, 0.86)',
    '--scrim': 'rgba(0, 0, 0, 0.60)',
    '--hero-bright': '0.55',
    '--gauge-track': 'rgba(255, 255, 255, 0.11)',
    '--shadow': '0 1px 0 rgba(0, 0, 0, 0.5), 0 24px 50px -30px rgba(0, 0, 0, 0.95)',
    '--shadow-ember': '0 0 0 1px rgba(216, 137, 74, 0.22), 0 28px 70px -34px rgba(216, 137, 74, 0.50)',
    '--inner-glow': 'inset 0 1px 0 rgba(255, 255, 255, 0.09)',
    // brushed-metal hairline stops (light scratches on a dark metal)
    '--hair-lo': 'rgba(255, 255, 255, 0.045)',
    '--hair-mid': 'rgba(255, 255, 255, 0.11)',
    '--hair-hi': 'rgba(255, 255, 255, 0.27)',
    '--hair-lo2': 'rgba(255, 255, 255, 0.09)',
    '--hair-mid2': 'rgba(255, 255, 255, 0.18)',
    '--hair-hi2': 'rgba(255, 255, 255, 0.36)',
    'color-scheme': 'dark',
};

const LIGHT = {
    '--bg-0': '#efeeea',
    '--bg-1': '#f7f6f2', // DERIVED: the lifted card ground
    '--bg-2': '#e6e5e0', // 6F --bg-2
    '--bg-3': '#e3e1db', // 6F --stage
    '--stage': '#e3e1db',
    '--surface': '#ffffff',
    '--surface-2': '#f4f3ef', // DERIVED
    '--pop': '#ffffff',
    '--pop-line': 'rgba(28, 28, 31, 0.16)',
    '--line': 'rgba(28, 28, 31, 0.13)',
    '--line-mid': 'rgba(28, 28, 31, 0.22)',
    '--line-strong': 'rgba(28, 28, 31, 0.34)',
    '--frame': 'rgba(28, 28, 31, 0.16)',
    '--text': '#1c1c1f',
    '--text-2': '#4c4a46',
    '--text-3': '#67645c',
    '--text-4': '#9d998e',
    '--warn': '#c0392b',
    // accent on light: --gold is consumed as TEXT far more than as a fill (run
    // R13 1a audit: 205 findings at 3.80–4.28:1 with the stroke value #a2601f),
    // so it resolves to the INK copper #8f4f16 (5.48:1 on #efeeea, 7.0:1 on
    // white). Fills use --ember (#b87231) directly — every .btn already does.
    '--gold': COPPER.emberInk,
    '--gold-dim': 'rgba(143, 79, 22, 0.10)', // 6F light --accent-soft
    '--gold-glow': 'rgba(143, 79, 22, 0.08)',
    '--on-gold': '#ffffff',
    '--ember': COPPER.lightFill,
    '--ember-text': COPPER.emberInk,
    '--ember-ink': COPPER.emberInk,
    '--ember-lift': COPPER.lightLift,
    '--ember-on': COPPER.emberOn,
    '--accent-soft': 'rgba(143, 79, 22, 0.10)',
    '--accent-line': 'rgba(143, 79, 22, 0.36)',
    '--accent-glow': COPPER.lightStroke,
    '--accent-ink': COPPER.emberInk,
    '--neon': '#2e7d32',
    '--orange': '#b45309',
    '--blue': '#1d6fa5',
    '--header-bg': 'rgba(239, 238, 234, 0.86)',
    '--scrim': 'rgba(239, 238, 234, 0.72)',
    '--hero-bright': '0.92',
    '--gauge-track': 'rgba(28, 28, 31, 0.14)',
    '--shadow': '0 1px 2px rgba(28, 28, 31, 0.06), 0 18px 40px -28px rgba(28, 28, 31, 0.38)',
    '--shadow-ember': '0 0 0 1px rgba(143, 79, 22, 0.20), 0 24px 60px -32px rgba(143, 79, 22, 0.42)',
    '--inner-glow': 'inset 0 1px 0 rgba(255, 255, 255, 0.92)',
    // brushed-metal hairline stops (dark scratches on a light metal)
    '--hair-lo': 'rgba(28, 28, 31, 0.05)',
    '--hair-mid': 'rgba(28, 28, 31, 0.13)',
    '--hair-hi': 'rgba(28, 28, 31, 0.26)',
    '--hair-lo2': 'rgba(28, 28, 31, 0.10)',
    '--hair-mid2': 'rgba(28, 28, 31, 0.20)',
    '--hair-hi2': 'rgba(28, 28, 31, 0.34)',
    'color-scheme': 'light',
};

// The map is FIXED DARK in both themes (6F): its own scale, hand-tuned, and it
// re-pins the dark copper + dark hairline stops so a light page cannot bleed
// onto it. Applied as `.on-map`.
const MAP = {
    '--map': '#0f0f13',
    '--map-2': '#111114',
    '--map-land': '#232328',
    '--map-land-line': '#3a3a41',
    '--map-panel': '#212126',
    '--map-ctl': 'rgba(42, 42, 46, 0.94)',
    '--map-grid': 'rgba(255, 255, 255, 0.045)',
    '--map-shop': '#e6e3dc',
    '--map-ember': COPPER.ember,
    '--map-ember-t': COPPER.emberText,
    '--map-ember-2': '#eeb27e',
};

// Theme-independent: type, radius, tracking, the composed hairlines, aliases.
const STATIC = {
    // Type. next/font emits the *-loaded variables on <html> (app/layout.tsx);
    // these names are what the app reads. Manrope carries display AND body in
    // 6F (800 display / 400–700 body); JetBrains Mono stays for ids and money.
    // Display and body are the same loaded Manrope (one next/font instance);
    // display differs by weight (800) and tracking, not family.
    '--font-display': "var(--font-body-loaded, 'Manrope'), 'Segoe UI', system-ui, -apple-system, 'Helvetica Neue', Arial, sans-serif",
    '--font-body': "var(--font-body-loaded, 'Manrope'), 'Segoe UI', system-ui, -apple-system, 'Helvetica Neue', Arial, sans-serif",
    '--font-mono': "var(--font-mono-loaded, 'JetBrains Mono'), Menlo, Consolas, ui-monospace, monospace",
    '--font-jp': "var(--font-jp-loaded, 'Noto Sans JP'), var(--font-body)",
    // Tracking. 6F: display -0.028em, headings -0.02em, uppercase meta +.06/.10em.
    '--track-tight': '-0.02em',
    '--track-display': '-0.028em',
    '--track-wide': '0.06em',
    '--track-wider': '0.10em',
    '--track-widest': '0.12em',
    // Radius. The old site was radius-0 by design; 6F is 12–20 with pills.
    '--radius-sm': '6px',
    '--radius-md': '14px',
    '--radius-card': '18px',
    '--radius-lg': '20px',
    '--radius-pill': '999px',
    // The brushed-metal hairline: a 115° gradient of the six stops (6F).
    '--hair': 'linear-gradient(115deg, var(--hair-lo) 0%, var(--hair-hi) 13%, var(--hair-mid) 26%, var(--hair-hi) 42%, var(--hair-lo) 57%, var(--hair-mid) 71%, var(--hair-hi) 86%, var(--hair-lo) 100%)',
    '--hair-s': 'linear-gradient(115deg, var(--hair-lo2) 0%, var(--hair-hi2) 13%, var(--hair-mid2) 26%, var(--hair-hi2) 42%, var(--hair-lo2) 57%, var(--hair-mid2) 71%, var(--hair-hi2) 86%, var(--hair-lo2) 100%)',
    '--hair-ember': 'linear-gradient(115deg, rgba(216, 137, 74, 0.20) 0%, rgba(216, 137, 74, 0.78) 20%, rgba(216, 137, 74, 0.34) 45%, rgba(216, 137, 74, 0.72) 72%, rgba(216, 137, 74, 0.24) 100%)',
    // Photo bands: fixed ink, both themes (6F --ink-photo / --on-photo*).
    '--ink-photo': '#0e0e11',
    '--on-photo': '#ffffff',
    '--on-photo-2': 'rgba(255, 255, 255, 0.80)',
    '--on-photo-ember': '#f2b481',
    // Aliases for names the app used before they were defined (see the history
    // in git for the measured list). They hold the token STREAM, so they follow
    // whichever theme block is in force.
    '--text-dim': 'var(--text-3)',
    '--text-1': 'var(--text)',
    '--bg-hover': 'var(--bg-3)',
    '--surf-1': 'var(--surface)',
    '--surf-2': 'var(--surface-2)',
    '--rule': 'var(--line)',
    '--bdr': 'var(--line)',
    '--danger': 'var(--warn)',
    '--accent': 'var(--gold)',
    // The hero band is a photo band now: fixed ink, like every photo surface.
    '--hero-band-end': '#0e0e11',
    '--hero-band-ink': '#ffffff',
    '--hero-band-ink-2': 'rgba(255, 255, 255, 0.72)',
};

// ── Emit ──────────────────────────────────────────────────────────────────────
const decl = (obj, indent = '  ') =>
    Object.entries(obj)
        .map(([k, v]) => `${indent}${k}: ${v};`)
        .join('\n');

const block = (selector, obj, comment) =>
    `${comment ? `/* ${comment} */\n` : ''}${selector} {\n${decl(obj)}\n}\n`;

const region = [
    BEGIN,
    '',
    block(':root', { ...DARK, ...STATIC }, 'DARK — the default. Copper Map 6F values; STATIC tokens (type, radius, hairlines, aliases) live here once.'),
    block(
        ":root[data-theme='light'],\n.shop-layout[data-theme='light'],\n.light-scope",
        LIGHT,
        'LIGHT — an explicit choice: the rollout_theme cookie stamped on <html>, the console\'s own data-theme, or a .light-scope subtree.',
    ),
    `/* LIGHT by system preference, only when nothing explicit is stamped. */\n@media (prefers-color-scheme: light) {\n  :root:not([data-theme]) {\n${decl(LIGHT, '    ')}\n  }\n}\n`,
    block(".shop-layout[data-theme='dark']", DARK, 'A dark console inside a light site — the console\'s own choice beats the page.'),
    block('.on-dark', { ...DARK }, 'A permanently dark PHOTO surface in any theme: the whole set, backgrounds included, or inner boxes vanish (measured, run R12).'),
    block(
        '.on-map',
        { ...MAP, ...DARK, '--ember': 'var(--map-ember)', '--ember-text': 'var(--map-ember-t)', '--accent-ink': 'var(--map-ember-t)', '--accent-glow': 'var(--map-ember)', '--gauge-track': 'rgba(255, 255, 255, 0.12)', 'color': 'var(--text)' },
        'The map: FIXED DARK in both themes (6F). Its own scale plus the dark copper and dark hairline stops re-pinned, so a light page cannot bleed onto it.',
    ),
    `/* The map never carries glass: no backdrop-filter over tiles (mobile GPU, and 6F's rule). */\n.on-map,\n.on-map * {\n  backdrop-filter: none !important;\n  -webkit-backdrop-filter: none !important;\n}\n`,
    END,
].join('\n');

const css = fs.readFileSync(CSS, 'utf8');
const nl = css.includes('\r\n') ? '\r\n' : '\n';
const b = css.indexOf(BEGIN);
const e = css.indexOf(END);
if (b < 0 || e < 0) {
    console.error('globals.css has no TOKENS markers — insert them once by hand around the old token blocks, then run again.');
    process.exit(1);
}
const next = css.slice(0, b) + region.replace(/\n/g, nl) + css.slice(e + END.length);
if (process.argv.includes('--check')) {
    if (next !== css) {
        console.error('globals.css token region is STALE — run node scripts/gen-tokens.mjs');
        process.exit(1);
    }
    console.log('token region is current');
    process.exit(0);
}
fs.writeFileSync(CSS, next);
console.log(`globals.css token region regenerated (${region.split('\n').length} lines)`);
